#/Library/Ruby/Gems/2.6.0/gems/minima-2.5.1/

title: Ephram's Book Reviews
#author: Ephram Stevens
#email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Reviews of children's book by an avid reader.

show_excerpts: false # set to true to show excerpts on the homepage

kramdown:
  auto_ids: true

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

header_pages:
- posts.md

# generate social links in footer
#twitter_username: Glue_X
#facebook_username: GlueXperiment
#instagram_username: gluexexperiment

# Build settings
theme: minima
#theme: minimal-mistakes-jekyll
#theme: minimal
#theme: hyde

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-gist
